version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./IMS
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./IMS:/var/www/html/
        ports:
            - 80:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: shop_inventory
            MYSQL_USER: ubuntu
            MYSQL_PASSWORD: Ubuntu@123
        ports:
            - "3306:3306"
